version: '3'
services:
  ubuntu:
    image: ntno/ubuntu-build-base:1.0.0
    restart: "no"    
    volumes:
      - $PWD:/usr/src
  local_examples_server:
    image: ntno/ubuntu-base:0.0.1
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      LOG_LEVEL: info 
    volumes:
      - './:/usr/src/'
    working_dir: '/usr/src/tests/examples/'
  local_documentation_server:
    image: ntno/ubuntu-build-base:1.0.0
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug 
    volumes:
      - './:/usr/src/'      
    working_dir: '/usr/src/documentation'