GITHUB_LINK_HREF = "https://github.com"
GITHUB_LINK_TEXT = "github.com"
GITHUB_LINK_TITLE = "go to GitHub"
GITHUB_LINK_TARGET = "_blank"
GITHUB_IMG_SRC = "https://github.githubassets.com/favicons/favicon.svg"
GITHUB_IMG_ALT = "the GitHub Octopuss logo"
GITHUB_IMG_TITLE = "GitHub's Octopuss logo"
GITHUB_IMG_WIDTH = "100"
GITHUB_IMG_HEIGHT = "200"
GITHUB_CAPTION = "an example logo"
GH_REPO_SOURCE_SITE_NAME = "GitHub"
GH_REPO_URL = "https://github.com/myUsername/myRepository"
GH_REPO_EDIT_URI_TEMPLATE = "https://github.com/myUsername/myRepository/edit/main/docs/{path}"
BB_REPO_SOURCE_SITE_NAME = "Bitbucket"
BB_REPO_URL = "https://bitbucket.org/norganick/myUsername/myRepository"
BB_REPO_EDIT_URI_TEMPLATE = "src/main/docs/{path}?mode=edit"
