GITHUB_LINK_HREF = "https://github.com"
GITHUB_TEXT = "github.com"
GITHUB_TITLE = "go to GitHub"
GITHUB_IMG_SRC = "https://github.githubassets.com/favicons/favicon.svg"
GITHUB_IMG_ALT = "the GitHub Octopuss logo"
GITHUB_IMG_WIDTH = "100"
GITHUB_IMG_HEIGHT = "200"
GITHUB_CAPTION = "an example logo"
