INHERIT: ./mkdocs.yml

theme:
  name: null
  custom_dir: '../terminal'
  features:
    # - navigation.side.hide
    - navigation.side.indexes
    # - navigation.side.toc.hide
    # - navigation.top.hide
    # - navigation.top.cursor_animation.hide
    # - navigation.top.search_button.hide
    - revision.date
    - revision.history
  static_templates:
    - 404.html

plugins:
  - terminal/md-to-html
  - git-revision-date
  - search
  - macros:
      verbose: true
      modules: [mkdocs-terminal:terminal.pluglets.tile_grid]
      #
      # module_name: markup
      # include_dir: markup

  # modules: [mkdocs-macros-test-ntno:mkdocs_macros_test]
watch:
  - '../terminal/partials'
  - '../terminal/macros'
  - '../terminal/pluglets'
  - './mkdocs.yml'