INHERIT: ./mkdocs.yml

theme:
  name: null
  custom_dir: '../terminal'
  features:
    - navigation.side.indexes
    - revision.date
    - revision.history

watch:
  - '../terminal'
  - './mkdocs.yml'