INHERIT: ./mkdocs.yml

theme:
  name: null
  custom_dir: '../terminal'
  features:
    # - navigation.side.hide
    - navigation.side.indexes
    # - navigation.side.toc.hide
    # - navigation.top.hide
    # - navigation.top.cursor_animation.hide
    # - navigation.top.search_button.hide
    - revision.date
    - revision.history
  static_templates:
    - 404.html

plugins:
  - terminal/md-to-html
  - macros:
      verbose: true
      modules: [mkdocs-terminal:terminal.pluglets.tile_grid.main]

watch:
  - '../terminal/partials'
  - '../terminal/macros'
  - './mkdocs.yml'