INHERIT: ./mkdocs.yml

theme:
  name: null
  custom_dir: '../terminal'
  features:
    - footer.prev_next
    # - navigation.side.hide
    - navigation.side.indexes
    # - navigation.side.toc.hide
    # - navigation.top.hide
    # - navigation.top.cursor_animation.hide
    # - navigation.top.search_button.hide
    - revision.date
    - revision.history
    # - style.links.underline.hide
  static_templates:
    - 404.html
    - about/coverage-report/index.html

plugins:
  - terminal/md-to-html
  - git-revision-date
  # - search
  # - exclude-search:      
  #     exclude:
  #       - overrides
  #       - about/coverage-report/*
  #       - configuration/palettes/*
  #       - elements/examples/*
  #     ignore:
  #       - configuration/palettes/index.md#theme-color-palettes
  #       - configuration/palettes/dark.md#dark-palette
  #       - configuration/palettes/default.md#default-palette
  #       - configuration/palettes/gruvbox-dark.md#gruvbox-dark-palette
  #       - configuration/palettes/pink.md#pink-palette
  #       - configuration/palettes/sans-dark.md#sans-dark-palette
  #       - configuration/palettes/sans.md#sans-palette
  - macros:
      verbose: true
      modules:
        - mkdocs-terminal:terminal.pluglets.tile_grid.main

watch:
  - '../terminal/css'
  - '../terminal/partials'
  - '../terminal/base.html'
  - '../terminal/macros'
  - '../terminal/pluglets/tile_grid/templates'
  - './mkdocs.yml'