name: Test Package

on: 
  pull_request:
    types: [ synchronize ]

jobs:
  vault-install:
    runs-on: ubuntu-latest
    steps:
      - name: manual-install
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

  test:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - if: ${{ matrix.platform == 'ubuntu-latest' }} 
        name: (ubuntu) Install Testing Prereqs
        run: |
          make USE_SUDO=1 install-test-prereqs
      - if: ${{ matrix.platform == 'macos-latest' }} 
        name: (macos) Install Testing Prereqs
        run: |
          git clone https://github.com/htacg/tidy-html5.git
          cd tidy-html5/build/cmake
          cmake ../.. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release "-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64"
          make 
          sudo make install
      - name: Install Tox
        run: make install-tox
      - name: Test Build/Package with Tox
        run: python -m tox -e py
      - if: ${{ matrix.platform == 'ubuntu-latest' }} 
        name: (ubuntu) Run Tox pytests
        run: |
          python -m tox -e pytest-linux
      - if: ${{ matrix.platform == 'macos-latest' }} 
        name: (macos) Run Tox pytests
        run: |
          python -m tox -e pytest-darwin
          